### ISSUE TITLE
Bug: argument error for escape_character

### ISSUE THREAD

**Issue by frankdugan3** [beatrichartz/csv#122]
**If this is a bug, steps to reproduce it**

With recent versions of Elixir/OTP, CSV will raise an argument error when attempting to decode:

```
iex(5)> CSV.decode("")
** (ArgumentError) construction of binary failed: segment 1 of type 'utf8': expected a non-negative integer encodable as utf8 but got: nil
    (csv 3.0.5) lib/csv/decoding/parser.ex:156: CSV.Decoding.Parser.get_escape/1
    (csv 3.0.5) lib/csv/decoding/parser.ex:64: CSV.Decoding.Parser.parse_into_rows/2
    (csv 3.0.5) lib/csv/decoding/decoder.ex:159: CSV.Decoding.Decoder.decode/2
    (csv 3.0.5) lib/csv.ex:154: CSV.decode/2
```
```
iex(5)> CSV.decode("", escape_character: ?")
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not a valid pattern

    (stdlib 4.3.1) :binary.compile_pattern([",", "\"", 13, 10])
    (csv 3.0.5) lib/csv/decoding/parser.ex:139: CSV.Decoding.Parser.create_token_pattern/1
    (csv 3.0.5) lib/csv/decoding/parser.ex:65: CSV.Decoding.Parser.parse_into_rows/2
    (csv 3.0.5) lib/csv/decoding/decoder.ex:159: CSV.Decoding.Decoder.decode/2
    (csv 3.0.5) lib/csv.ex:154: CSV.decode/2
```

I have verified that if I replace line 156 of [`lib/csv/decoding/parser.ex`](https://github.com/beatrichartz/csv/blob/main/lib/csv/decoding/parser.ex#L156) with a literal escape, such as `"\""`, I am able to successfully decode CSV files without the argument error.

- Include steps to reproduce the issue
  - elixir 1.14.5/1.15.0-rc.0
  - erlang 25.3.2/26.0
  - `CSV.decode("")` or `CSV.decode("", escape_character: ?")`
- Is your input CSV [RFC 4180](https://tools.ietf.org/html/rfc4180) compliant?
    N/A
- Are you interested in helping with a PR?
    yes
    
    
Edit: I am having trouble reproducing this directly in CSV, only when using in another app. I removed the `mix.lock` file, and completely removed both `deps` and `_build` folders to ensure a clean build, and all of the deps are at the latest, but this issue is still persisting. :thinking:

**Comment by frankdugan3** [comment]
Further followup: I tried downgrading Elixir/OTP to the latest version in the CSV CI matrix, that didn't help, so maybe the Elixir/OTP verion is a red herring. I had the same issue with CSV `2.5.0`, and had to revert CSV to `2.4.1` to get back to a working state. With CSV `2.4.1`, I can run Elixir `1.14.5`/OTP `26.0` with no trouble.

I'm not sure how to figure out what's going on at this point. One far-fetched possibility is that I have a lot of dependencies in this project, and it's possible there are some conflicts? I noticed this in the compiler output:

```
mix compile csv --force
==> csv
Compiling 7 files (.ex)
warning: redefining module CSV.Defaults (current version loaded from /home/frank/git/hsm/_build/dev/lib/licensir/ebin/Elixir.CSV.Defaults.beam)
  lib/csv/defaults.ex:1

warning: redefining module CSV.Encoding.Encoder (current version loaded from /home/frank/git/hsm/_build/dev/lib/licensir/ebin/Elixir.CSV.Encoding.Encoder.beam)
  lib/csv/encoding/encoder.ex:1

warning: redefining module CSV.Encode (current version loaded from /home/frank/git/hsm/_build/dev/lib/licensir/ebin/Elixir.CSV.Encode.beam)
  lib/csv/encoding/encode.ex:1

warning: undefined module attribute @unescape_formulas, please remove access to @unescape_formulas or explicitly set it before access
  lib/csv/decoding/parser.ex:88: CSV.Decoding.Parser (module)

warning: undefined module attribute @escape_formula_start, please remove access to @escape_formula_start or explicitly set it before access
  lib/csv/decoding/parser.ex:91: CSV.Decoding.Parser (module)

warning: undefined module attribute @escape_character, please remove access to @escape_character or explicitly set it before access
  lib/csv/decoding/parser.ex:156: CSV.Decoding.Parser (module)

warning: redefining module CSV.Encode.Any (current version loaded from /home/frank/git/hsm/_build/dev/lib/licensir/ebin/Elixir.CSV.Encode.Any.beam)
  lib/csv/encoding/encode.ex:14

warning: redefining module CSV.Encode.BitString (current version loaded from /home/frank/git/hsm/_build/dev/lib/licensir/ebin/Elixir.CSV.Encode.BitString.beam)
  lib/csv/encoding/encode.ex:25
```

**Comment by frankdugan3** [comment]
OK, verified it was `licensir` that was causing the problem. The project is now unmaintained now and used old CSV APIs, so removing it solves the problem. Sorry for the noise!
