### ISSUE TITLE
Support for csv in strings?

### ISSUE THREAD

**Issue by gouthamvel** [beatrichartz/csv#23]
I'm getting a error when trying to use csv on strings rather than reading from file

```elixir
iex(23)> string = "a,1
...(23)> b,4"
"a,1\nb,4"
iex(24)> string |> CSV.decode  |> Enum.map fn r -> Enum.map(r, &String.upcase/1) end
** (Protocol.UndefinedError) protocol Enumerable not implemented for "a,1\nb,4"
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:112: Enumerable.reduce/3
    (elixir) lib/stream.ex:1240: Enumerable.Stream.do_each/4
    (elixir) lib/stream.ex:700: Stream.do_transform/8
    (elixir) lib/enum.ex:1400: Enum.reduce/3
    (elixir) lib/enum.ex:1047: Enum.map/2
iex(24)> File.stream!("/Users/username/test_data.csv") |> CSV.decode  |> 
iex(25)>Enum.map fn r -> Enum.map(r, &String.upcase/1) end
[["A", "1"], ["B", "4"]]
iex(26)>
```

the contents of test_data.csv are same as string used
Is there anything wrong i'm doing or are strings not supported?

PS: i'm fairly new to functional programing/elixir world.

**Comment by beatrichartz** [comment]
The input to CSV is required to be enumerable - that means if you have a string you could e.g. split it by line with [`String.split`](http://elixir-lang.org/docs/v1.0/elixir/String.html#split/3):

```elixir
string = "a,1\nb,4"
string |> String.split("\n") |> CSV.decode  |> Enum.map fn r -> Enum.map(r, &String.upcase/1) end
```
Curious, what's the exact usecase?

**Comment by gouthamvel** [comment]
Its working thanks.
